version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    restart: always

  database:
    build:
      context: .
      dockerfile: Dockerfile.bdd
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: gfloret
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
    ports:
      - 9906:3306

  php:
    image: php7.1-fpm
    container-name: php
    depends_on:
      - database
    ports:
      9000:9000

  web:
    build:
      context: .
    container_name: cdpphp
    ports:
      - 8100:80
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./:/var/www/html